AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus HTTP - ECCShopDB

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod

Resources:
  ECCShopDB:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub eccshopdb-${Environment}-api
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: target/function.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
          SHOPDB_API_USERNAME: !Sub "{{resolve:ssm:eccshopdb-api-username-${Environment}}}"
          QUARKUS_DATASOURCE_USERNAME: !Sub "{{resolve:ssm:eccshopdb-postgresql-username-${Environment}}}"
          QUARKUS_DATASOURCE_PASSWORD: !Sub "{{resolve:ssm:eccshopdb-postgresql-password-${Environment}}}"
          QUARKUS_DATASOURCE_JDBC_URL: !Sub "{{resolve:ssm:eccshopdb-postgresql-jdbc-url-${Environment}}}"
          QUARKUS_TRANSACTION_MANAGER_DEFAULT_TRANSACTION_TIMEOUT: 1800
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  ECCShopDBAPI:
    Description: ECCShopDB API URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    Export:
      Name: ECCShopDBAPI
