version=0.1

[dev.deploy.parameters]
stack_name = "eccshopdb-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jsap9fy7hglm"
s3_prefix = "eccshopdb-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []

[prod.deploy.parameters]
stack_name = "eccshopdb-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jsap9fy7hglm"
s3_prefix = "eccshopdb-prod"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\""
image_repositories = []